name: CI
on:
  push:
    branches:
      - '**'

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Deps
        run: pnpm install --frozen-lockfile

  run_lint:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint

  run_format:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: Format
        run: pnpm format

  run_typecheck:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm typecheck

  run_test:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - run_lint
      - run_format
      - run_typecheck
      - run_test

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Creating .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          echo "@cut0:registry=https://npm.pkg.github.com" >> .npmrc

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
